### ISSUE TITLE
check that .travis file is templated correctly

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/suitcase-cookiecutter#3]
Saw a spurious 3.5 in the .travis.yml for suitcase-csv

**Comment by danielballan** [comment]
Is the point of this issue just "Drop 3.5 builds in `.travis.yml`"? We intentionally had 3.5 support, and then last week we made the decision to drop it, now implemented in #5.

The title is confusing me --- is there something wrong with the template?

**Comment by tacaswell** [comment]
I thought it asked you what versions to support, but may have crossed the two cookiecutters...

**Comment by danielballan** [comment]
Ah, yes. The scipy cookiecutter prompts; this one has a hard-coded opinion.

Closed by #5.

**Comment by tacaswell** [comment]
:+1: sorry for the noise.
