### ISSUE TITLE
add templated pytest.ini and .coveragerc files

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/suitcase-cookiecutter#4]
See https://github.com/NSLS-II/suitcase-csv/pull/1/commits/1ac53e2d0af24c9ef396c4aa0d07b8cc4abc873e and https://github.com/NSLS-II/suitcase-csv/pull/1/commits/51e2fec7d3663aaf233bf8c4686d708aeacb2923

**Comment by danielballan** [comment]
Done in #13
